### ISSUE TITLE
What is the DEEP_RCNN_FUSION?

### ISSUE THREAD

**Issue by ssolchoi** [happinesslz/EPNetV2#2]
Thanks for your great job:)

What is the DEEP_RCNN_FUSION?

**Comment by happinesslz** [comment]
@ssolchoi DEEP_RCNN_FUSION means  achieving multi-modal fusion in ROI-wise level in the RCNN stage. However, this setting is not included in EPNet++。

**Comment by ssolchoi** [comment]
Thank you for answer.

Additionally, eval_rcnn cgf has a val option. Should I change it to test when submitting with kitti performance?
(However, if you change it to test, an error occurs saying there is no train_mask.)

When submitting performance to kitti, data should be saved as 00000.txt ..., but it is saved from 000001.txt. Is there something I need to make additional corrections to?

Thank you for your reply.
