### ISSUE TITLE
Implement EPNet on Waymo dataset

### ISSUE THREAD

**Issue by Rolandxx7** [happinesslz/EPNetV2#4]
Hi lz, 

Thanks for your great contribution!
I recently tried to replicate EPNet on the Waymo dataset. My initial idea was to borrow the waymo_dataset.py provided by mmdet3d and then process the returned data into the data and format required by EPNet. 
However, after a few days' work, I feel such implementation seems very difficult, so I would like to ask you about the implementation process. Another question is whether we only need to rewrite the waymo_dataset.py code file.

Best regards.

**Comment by happinesslz** [comment]
@Rolandxx7 We implement EPNet++~(voxel-based version) on waymo dataset based on  the framework of OpenPCdet. For mmdetection3d, we think you can refer to TransFusion (See: https://github.com/XuyangBai/TransFusion/blob/master/configs/transfusion_waymo_voxel_LC.py), which provides the multi-modal fusion code on Waymo dataset.

**Comment by Rolandxx7** [comment]
> @Rolandxx7 We implement EPNet++~(voxel-based version) on waymo dataset based on the framework of OpenPCdet. For mmdetection3d, we think you can refer to TransFusion (See: https://github.com/XuyangBai/TransFusion/blob/master/configs/transfusion_waymo_voxel_LC.py), which provides the multi-modal fusion code on Waymo dataset.

Hi  @happinesslz ,

Thanks for your reply. I'm sorry you may not have understood my question.
What I want to do is replicate EPNet on the Waymo dataset based on your original EPNet code instead of using the mmdetection3d framework or Openpcdet framework. I used mmdetection3d's waymo_dataset.py before just to copy how waymo_dataset.py should be written instead of using the mmdetection3d framework.  So my question is how to implement EPNet based on the code architecture of the original EPNet on Waymo dataset, because I think it's a bit difficult to implement with my previous approach.

Best regards.

**Comment by Rolandxx7** [comment]
@happinesslz Sorry to bother you again. Could you please help me with this above question?

**Comment by happinesslz** [comment]
@Rolandxx7  Very sorry.  In fact,  we implement EPNet++/EPNet (voxel-based instead of point-based) on Waymo dataset by using OpenPCDet.  For original EPNet, it is difficulty to implement on Waymo dataset. Maybe you could convert Waymo to KITTI format and have a try on original EPNet.

**Comment by Rolandxx7** [comment]
> @Rolandxx7 Very sorry. In fact, we implement EPNet++/EPNet (voxel-based instead of point-based) on Waymo dataset by using OpenPCDet. For original EPNet, it is difficulty to implement on Waymo dataset. Maybe you could convert Waymo to KITTI format and have a try on original EPNet.

@happinesslz 
Thanks for your kind reply.
I still have a question. Compared to using OpenPCDet, I wonder what the difficulty is in replicating the original EPNet on Waymo dataset.

**Comment by happinesslz** [comment]
@Rolandxx7   Hi, the difficulties are as follows 1) You could need modify this code for supporting multi-class  ~(Cars, Pedestrians and Cyclists) training;  2) The framework of original  EPNet is too old and does not support distributed training, which is important to save  time for training the large-scale Waymo dataset.
